import { useContext, useEffect } from "react";
import Head from "next/head";
import { useWallet } from "use-wallet";
//
import { AppContext } from "../hooks/context";
//
export default function Home() {
  const wallet = useWallet();
  const { walletState, walletActions } = useContext(AppContext);

  const _handleActivateWallet = () => {
    wallet.connect();
  };

  const _handleInActivateWallet = () => {
    walletActions.unsetWalletAddress();
    wallet.reset();
  };

  useEffect(() => {
    const { walletAddress } = walletState;
    if (wallet && wallet.account && !walletAddress) {
      walletActions.setWalletAddress({
        walletAddress: wallet.account,
      });
    }
  });

  const { walletAddress } = walletState;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <button
          suppressHydrationWarning
          onClick={
            walletAddress ? _handleInActivateWallet : _handleActivateWallet
          }
        >
          {walletAddress
            ? walletAddress.slice(0, 4) +
              "..." +
              walletAddress.slice(
                walletAddress.length - 6,
                walletAddress.length
              )
            : "Connect Wallet"}
        </button>
      </div>
    </div>
  );
}
